version: 2.1

orbs:
 aws-cli: circleci/aws-cli@1.3.0
 aws-eks: circleci/aws-eks@1.0.2
 aws-ecr: circleci/aws-ecr@6.13.0
 trivy: fifteen5/trivy-orb@1.0.0
 xmatters: xmatters/xmatters-orb@1.0.4

jobs:
  
  code-scan:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - trivy/scan:
          args: 'fs --format sarif --output trivy-fs-results.sarif --exit-code 1 --vuln-type "os,library" --security-checks config --severity "MEDIUM,HIGH,CRITICAL" ./'
          version: '0.31.3'
      - store_artifacts:
          path: ./trivy-fs-results.sarif
          destination: trivy-fs-results.sarif

  # Add this job to all workflows
  disable-enable:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo ${CIRCLECISECRET}
      - run:
          name: Check contexts environment name
          shell: /bin/bash
          command: |
              if [[ $CIRCLECISECRET == 'circleci' ]]; then
                   echo "Switch context to circle"
                   exit 0
                 else 
                   echo "Switch context to githubactions"
              fi
              exit 99
  # This is example jobs
  exit1:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: Run commands
          command: |
              echo "I will exit fail status"
              exit 1

      - xmatters/notify:
          recipients: Engineering Managers
          when: on_fail

      - run:
          name: Run on fail status
          command: |
              echo "I am result of above failed job"

  request-approval:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - xmatters/notify:
          recipients: Engineering Managers

  ok:
    docker:
      - image: cimg/node:lts
    steps:
      - run: echo "ok"

workflows:

  exit1-fail-workflows:
    jobs:
    - exit1
    - request-approval
    - hold:
        type: approval
        requires:
          - exit1
          - request-approval
    - ok:
        requires:
          - hold

# VS Code Extension Version: 1.5.0