version: 2.1

orbs:
  shellcheck: circleci/shellcheck@2.0.0

jobs:
  
  disable-enable:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run:
          name: Check contexts env name
          background: true
          command: |
            #while true; do
              #sleep 5
              #LATEST_COMMIT=$(git ls-remote $CIRCLE_REPOSITORY_URL | grep $CIRCLE_BRANCH | cut -f 1)
              if [ "${CIRCLE_BRANCH}" != "${DISABLE_CIRCLECI}" ]; then
                echo "Branch miss match"
              #  curl -X POST "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel?circle-token=$CIRCLE_API_TOKEN"
              fi
              exit 99
            #done

  release:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          command: |
            echo ${DISABLE_CIRCLECI}
      - run:  
          command: |
            echo ${CIRCLE_BRANCH}
      - run: npm install
      - run: npm build
      - run: npm publish

workflows:

  release-workflows:

    jobs:
      - release:
          requires:
            - disable-enable
          context:
          - DisableEnable

# VS Code Extension Version: 1.4.0