version: 2.1

#orbs:
#  shellcheck: circleci/shellcheck@2.0.0

jobs:
  
  disable-enable:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - when:
          condition:
            or:
              - and:
                - equal: [ main, $DISABLE_CIRCLECI ]
          steps:
            - run: echo $DISABLE_CIRCLECI
            - run: echo $CIRCLE_BRANCH


  release:
    docker:
      - image: cimg/node:lts
    steps:
      #- run:
      #    command: |
      #      echo ${DISABLE_CIRCLECI}
      #- run:  
      #    command: |
      #      echo ${CIRCLE_BRANCH}
      - run: npm install
      - run: npm build
      - run: npm publish

workflows:

  release-workflows:
    jobs:
    - disable-enable:
        context:
          - DisableEnable
    - release:
        requires:
          - "disable-enable"

# VS Code Extension Version: 1.4.0