version: 2.1
##
# The `GHA_Event` parameter will be populated with the value `release` when triggered by
# the GitHub workflow. This can be used in conditional statements to run a specific workflow
# for a specific event.
##

#parameters:
#  GHA_Event:
#    type: string
#    default: ""
#  GHA_Actor:
#    type: string
#    default: ""
#  GHA_Action:
#    type: string
#    default: ""
#  GHA_Meta:
#    type: string
#    default: ""
#  GHA_Tag:
#    type: string
#    default: ""
#  disable-circleci:
#    type: env_var_name
#    default: DISABLE_CIRCLECI

jobs:
  release:
#    when: 
#      and:
#      - equal: [ "yes" , << parameters.disable-circleci >>]
    docker:
      - image: cimg/node:lts
    steps:
      - when:
          condition:
            equal: [ $CIRCLE_BRANCH == $DISABLE_CIRCLECI ]
          steps:
#            - run: npm install
#            - run: npm build
#            - run: npm publish
            - run: echo ${DISABLE_CIRCLECI}
            - run: echo ${CIRCLE_BRANCH}
            - run: echo << pipeline.git.branch >>

workflows:
  release:
    # Do not edit this line. This configuration for enable or disable circleci. create by zeabix
    
#      equal: [ "yes" , << pipeline.parameters.disable-circleci >>]
    ############################################################################################
    jobs:
      - release:
#          when: 
#            equal: [ "no" , << parameters.disable-circleci >>]
          context:
          - DisableEnable
