on:
  push:
    branches:
      - "main"
      
jobs:

  delete-old-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.2.0
        with:
          repository: amornc/switch   # replace this with your own repository
          older-than-seconds: 86400                           # remove all workflow runs older than 1 day
        env:
         GH_TOKEN: ${{ secrets.CD_PAT }}