on:
  workflow_dispatch: #Please remove this line
      
jobs:

  delete-old-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: get workflow runs id
        shell: bash
        continue-on-error: true
        env:
         GH_TOKEN: ${{ secrets.CD_PAT }}
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/amornc/switch/actions/runs | jq '.workflow_runs | .[].id' >> runs-id.txt
          cat runs-id.txt
      - name: delete-old-workflow-runs
        shell: bash
        continue-on-error: true
        env:
         GH_TOKEN: ${{ secrets.CD_PAT }}
        run: |
          file="runs-id.txt"
          while read -r line; do
              echo "Delete old workflows runs"
              gh api \
              --method DELETE \
              -H "Accept: application/vnd.github+json" \
              /repos/amornc/switch/actions/runs/$line
          done <$file

