on:
  push:
    branches:
      - "main"
  
jobs:

  enable-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Create root directory
        run: |
          mkdir enable-circleci
          cd enable-circleci
      - name: Create directory
        shell: bash
        run: |
          file="repo.txt"
          while read -r line; do
              echo "$line"
              mkdir "$line"
              ls -lah
              cd $line
              git init
              git remote add $line https://${{ secrets.CD_PAT }}@github.com/amornc/$line.git
              git fetch $line
              git checkout $line/main -- .github
              ls -lah .github/workflows/
              cd ..
          done <$file
      - name: list
        shell: bash
        run: |
          pwd
          find . -name '*.yaml' >> workflows.txt
      - name: disable-github-workflows
        shell: bash
        env:
         GH_TOKEN: ${{ secrets.CD_PAT }}
        run: |
          file="repo.txt"
          while read -r line; do
              echo "$line"
              gh api \
              -H "Accept: application/vnd.github+json" \
              /repos/amornc/$line/actions/workflows | jd '.id'
          done <$file
