on:
  push:
    branches:
      - "main"
#  release:
#    types: [published]
  workflow_dispatch:
    inputs:
      run:
        description: 'Run workflows on github action'
        required: true
        default: false
        type: boolean
  
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    if: ${{ ! github.event.inputs.run }}
    steps:
      - name: trigger-circleci
        id: circleci
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
  
  trigger-github-action:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run }} 
    steps:
      - name: Print the ci to STDOUT
        id: github-actions
        run: echo  The tags are ${{ inputs.run }}
