on:
  push:
    branches:
      - "main"
  
jobs:

  enable-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Create root directory
        run: |
          mkdir enable-circleci
          cd enable-circleci
      - name: Create directory
        shell: bash
        env:
         GH_TOKEN: ${{ secrets.CD_PAT }}
        run: |
          file="repo.txt"
          while read -r line; do
              echo "$line"
              mkdir "$line"
              cd $line
              # initinal git repository
              git init
              git remote add $line https://${{ secrets.CD_PAT }}@github.com/amornc/$line.git
              git fetch $line
              git checkout $line/main -- .github
              # get workflows id 
              gh api \
              -H "Accept: application/vnd.github+json" \
              /repos/amornc/$line/actions/workflows | jq '.workflows | .[].id' >> $line-WorkflowId.txt
              cat $line-WorkflowId.txt
              # replace repository owner
              echo "/repos/amornc/$line/actions/workflows/" >> $line-WorkflowPath.txt
              ## replace workflow id
              #file=$line-WorkflowId.txt
              file=$line-WorkflowPath.txt
              while read -r REPO; do
                  sed -e 's/$/\/disable/' $line-WorkflowId.txt 
              done <$file
              cat $line-WorkflowId.txt
              cd ..
          done <$file
#      - name: list
#        shell: bash
#        run: |
#          #ls -lahR -I ".git"
#          #pwd
#          #find . -name '*.yaml' >> workflows.txt
#          #cat owner-repo.txt
#          file="repo.txt"
#          while read -r line; do
#              cd $line
#              cat $line-WorkflowPath.txt
#              cd ..
#          done <$file
#      - name: get workflows id
#        shell: bash
#        env:
#         GH_TOKEN: ${{ secrets.CD_PAT }}
#        run: |
#          file="repo.txt"
#          while read -r line; do
#              echo "$line"
#              gh api \
#              -H "Accept: application/vnd.github+json" \
#              /repos/amornc/$line/actions/workflows | jq '.workflows | .[].id' >> workflows-id.txt
#          done <$file 
#      - name: Upload workflows-id.txt
#        uses: actions/upload-artifact@v2
#        with:
#          name: workflows-id.txt
#          path: ./workflows-id.txt
#          if-no-files-found: error
#      - name: disable github workflows
#        shell: bash
#        env:
#         GH_TOKEN: ${{ secrets.CD_PAT }}
#        run: |
#          file="repo.txt"
#          while read -r line; do
#              echo "$line"
#              gh api \
#               --method PUT \
#               -H "Accept: application/vnd.github+json" \
#               /repos/amornc/$line/actions/workflows/33309412/disable
#          done <$file 
