on:
  push:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      run:
        description: 'Run workflows on github action'
        required: true
        default: false
        type: boolean
  
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run }}
    steps:
      - name: trigger-circleci
        id: circleci
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
  
  trigger-github-action:
    runs-on: ubuntu-latest
    if: ${{ ! github.event.inputs.run }} 
    steps:
      - name: Print the ci to STDOUT
#        id: github-actions
        run: echo  The tags are ${{ inputs.run }}

  step2:
    runs-on: ubuntu-latest
#    if: ${{ github.event.inputs.run }} 
    needs: [trigger-github-action]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'amornc/switch'
          ref: 'main'
          path: 'amornc/switch/blob/main/.github/workflows'
      - name: echo step 2
#        id: github-actions
        run: |
          ls -lah amornc/switch/blob/main/.github/workflows/.circleci
          ls -lah amornc/switch/blob/main/.github/workflows/.github/workflows
#      - name: edit github workflow file
#        working-directory: amornc/switch/blob/main/.github/workflows/.github/workflows
#        run: |
      - name: test yq
#        id: lookupSdkVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.jobs.step2.steps[1]' 'amornc/switch/blob/main/.github/workflows/.github/workflows/main.yml'
          
