on:
#  release:
#    types: [published]
  workflow_dispatch:
    inputs:
      ci:
        description: 'CI'
        required: true
        default: '' 
        type: choice
        options:
        - circleci
        - github-action
  
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    if:  ${{ inputs.ci }} == 'circleci' 
    steps:
      - name: trigger-circleci
        id: circleci
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
  
#  trigger-github-action:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Print the ci to STDOUT
#        if:  ${{ inputs.ci }} != 'circleci' 
#        id: github-actions
#        run: echo  The tags are ${{ inputs.ci }}