on:
  push:
    branches:
      - "main"

#  workflow_dispatch:
#    inputs:
#      run:
#        description: 'Run workflows on github action'
#        required: true
#        default: false
#        type: boolean
  
jobs:
#  trigger-circleci:
#    runs-on: ubuntu-latest
#    if: ${{ github.event.inputs.run }}
#    steps:
#      - name: trigger-circleci
#        id: circleci
#        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
#        env:
#          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
#  
#  trigger-github-action:
#    runs-on: ubuntu-latest
#    if: ${{ ! github.event.inputs.run }} 
#    steps:
#      - name: Print the ci to STDOUT
##        id: github-actions
#        run: echo  The tags are ${{ inputs.run }}

  enable-circleci:
    runs-on: ubuntu-latest
#    if: ${{ github.event.inputs.run }} 
#    needs: [trigger-github-action]
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup variables
        shell: bash
        run: | 
          sh echo.sh
      - name: Checkout
        run: |
          #git init
          git remote add loadtest https://${{ secrets.CD_PAT }}@github.com/nocnoc-loadtest.git
          git fetch loadtest
          git checkout loadtest/main -- .github
      - name: show switch value
        working-directory: .circleci
        run: |
          yq eval '.workflows.release' config.yml
#      - name: checkout switch repository
#        uses: actions/checkout@v3
#        with:
#          repository: $repo
#          ref: 'main'
#          path: 'amornc/$repo/blob/main/.github/workflows'
#          token: ${{ secrets.CD_PAT }}
#      - name: checkout switch repository
#        uses: actions/checkout@v3
#        with:
#          repository: 'amornc/switch'
#          ref: 'main'
#          path: 'amornc/switch/blob/main/.github/workflows'
#          token: ${{ secrets.CD_PAT }}
#      - name: checkout snocko-gold-trading repository
#        uses: actions/checkout@v3
#        with:
#          repository: 'amornc/snocko-gold-trading'
#          ref: 'main'
#          path: 'amornc/snocko-gold-trading/blob/main/.github/workflows'
#          token: ${{ secrets.CD_PAT }}
#      - name: echo switch repository
##        id: github-actions
#        run: |
#          ls -lah amornc/switch/blob/main/.github/workflows/.circleci
#          ls -lah amornc/switch/blob/main/.github/workflows/.github/workflows
#          find . -name '.git'
#      - name: echo snocko-gold-trading repository
##        id: github-actions
#        run: |
#          ls -lah amornc/snocko-gold-trading/blob/main/.github/workflows/.circleci
#          ls -lah amornc/snocko-gold-trading/blob/main/.github/workflows/.github/workflows
#          find . -name '.git'
#      - name: show switch value
#        working-directory: amornc/switch/blob/main/.github/workflows/.circleci
#        run: |
#          yq eval '.workflows.release.when' config.yml
#      - name: show snocko-gold-trading value
#        working-directory: amornc/snocko-gold-trading/blob/main/.github/workflows/.circleci
#        run: |
#          yq eval '.workflows.Dev_WorkFlow' config.yml
#      - name: edit snocko-gold-trading value
#        working-directory: amornc/snocko-gold-trading/blob/main/.github/workflows/.circleci
#        run: |
#          #sed -i 's/when: false/#when: false/g' config.yml
#          sed '/Dev_WorkFlow/ a #Next line is the 6th line, not this' sedtest.txt
#      - name: show switch value
#        working-directory: amornc/switch/blob/main/.github/workflows/.circleci
#        run: |
#          yq eval '.workflows.release' config.yml
#      - name: Commit & Push changes
#        run: |
#          cd amornc/switch/blob/main/.github/workflows
#          git config --global user.email 'DevOps'
#          git config --global user.name  'devops@zeabix.com'
#          git add .
#          git commit -m "Enable CircleCI workflows"
#          git push https://${{ secrets.CD_PAT }}@github.com/amornc/switch.git
#